import os
import pandas as pd

class ReportGenerator:
    @staticmethod
    def save_report(backtest_instance, stats, filename):
        """
        Generates a split-screen HTML report:
        Left: Interactive Chart
        Right: Performance Metrics Table
        """
        # 1. Generate the standard Bokeh plot to a temporary file
        temp_file = "temp_plot.html"
        backtest_instance.plot(filename=temp_file, open_browser=False)
        
        # 2. Read the generated HTML content
        with open(temp_file, "r", encoding="utf-8") as f:
            html_content = f.read()
        
        # 3. Clean up the Stats (Filter out heavy dataframes like 'Equity Curve')
        # We only want the summary metrics (scalars)
        metrics = stats[stats.apply(lambda x: not isinstance(x, (pd.DataFrame, pd.Series, list)))]
        metrics_df = pd.DataFrame(metrics).reset_index()
        metrics_df.columns = ["Metric", "Value"]
        
        # Format numbers (optional cleanup)
        metrics_df["Value"] = metrics_df["Value"].apply(lambda x: str(round(x, 4)) if isinstance(x, float) else str(x))
        
        # Convert to HTML Table
        table_html = metrics_df.to_html(index=False, classes="metrics-table", border=0)

        # 4. Define Custom CSS for the Split Layout
        custom_css = """
        <style>
            /* Force Body to be a Flex Container */
            body { 
                display: flex !important; 
                flex-direction: row !important; 
                margin: 0 !important; 
                padding: 0 !important; 
                height: 100vh !important; 
                overflow: hidden !important; 
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            }
            
            /* The Bokeh Chart (Left Side) */
            /* We target the main Bokeh container class */
            .bk-root { 
                flex: 1 1 auto !important; 
                width: 75% !important; 
                height: 100vh !important; 
                overflow: hidden !important;
            }
            
            /* The Metrics Panel (Right Side) */
            .side-panel { 
                flex: 0 0 350px; /* Fixed width for stats */
                height: 100vh; 
                overflow-y: auto; 
                background: #f8f9fa; 
                border-left: 2px solid #dee2e6; 
                padding: 20px; 
                box-shadow: -4px 0 10px rgba(0,0,0,0.05);
                z-index: 1000;
            }
            
            /* Table Styling */
            .metrics-table {
                width: 100%;
                border-collapse: collapse;
                background: white;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                border-radius: 5px;
                overflow: hidden;
            }
            .metrics-table thead { background: #007bff; color: white; }
            .metrics-table th, .metrics-table td { 
                padding: 10px 15px; 
                border-bottom: 1px solid #eee; 
                font-size: 13px;
            }
            .metrics-table tr:hover { background-color: #f1f1f1; }
            h2 { color: #333; font-size: 18px; margin-top: 0; }
        </style>
        """

        # 5. Define the Side Panel HTML
        side_panel_html = f"""
        <div class="side-panel">
            <h2>Strategy Performance</h2>
            {table_html}
            <br>
            <p style="font-size: 11px; color: #666;">Generated by Python Backtester</p>
        </div>
        """

        # 6. Inject the CSS and HTML into the existing file
        # Inject CSS before </head>
        html_content = html_content.replace("</head>", f"{custom_css}</head>")
        
        # Inject Side Panel before </body>
        html_content = html_content.replace("</body>", f"{side_panel_html}</body>")

        # 7. Save Final Report
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        # Cleanup temp file
        if os.path.exists(temp_file):
            os.remove(temp_file)
            
        print(f"Advanced report saved to: {filename}")
